// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeIbHzcV6037tbHMfdVK8Tw6u5yDE_yj8',
    appId: '1:410649775381:web:66d62a2ecaeca12c162d1c',
    messagingSenderId: '410649775381',
    projectId: 'aismile-v1',
    authDomain: 'aismile-v1.firebaseapp.com',
    databaseURL: 'https://aismile-v1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aismile-v1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiVuMWqiKNR2AXZTyucGkMwAPpJyCS3Ko',
    appId: '1:410649775381:android:759926708e31e484162d1c',
    messagingSenderId: '410649775381',
    projectId: 'aismile-v1',
    databaseURL: 'https://aismile-v1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aismile-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8jXXDILM1mILJUAuzASsweecqJHyUDzI',
    appId: '1:410649775381:ios:3eedd26adceeb66b162d1c',
    messagingSenderId: '410649775381',
    projectId: 'aismile-v1',
    databaseURL: 'https://aismile-v1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aismile-v1.appspot.com',
    iosClientId: '410649775381-bits8gnfo9migajsce7v8791kr84icm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.venus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8jXXDILM1mILJUAuzASsweecqJHyUDzI',
    appId: '1:410649775381:ios:c52ba93f4adc18bd162d1c',
    messagingSenderId: '410649775381',
    projectId: 'aismile-v1',
    databaseURL: 'https://aismile-v1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aismile-v1.appspot.com',
    iosClientId: '410649775381-tqlqsja2cdhus5tc9cnmkpgme64sqrd4.apps.googleusercontent.com',
    iosBundleId: 'com.example.venus.RunnerTests',
  );
}
