name: venus
description: AI Smile.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  flutter_svg: ^2.0.7
  firebase_auth: ^4.9.0
  flutter_bloc: ^8.1.3
  go_router: ^10.1.2
  equatable: ^2.0.5
  bloc: ^8.1.2
  hexcolor: ^3.0.1
  google_fonts: ^5.1.0
  eva_icons_flutter: ^3.1.0
  google_sign_in: ^6.1.5
  meta: ^1.9.1
  flow_builder: ^0.0.9
  cloud_firestore: ^4.9.1
  firebase_database: ^10.2.5
  flutter_pagination: ^0.0.8
  file_picker: ^5.5.0
  firebase_storage: ^11.2.7
  localstorage: ^4.0.1+4
  uuid: ^4.1.0
  intl: ^0.18.1
  url_strategy: ^0.2.0
  build_web_compilers: ^4.0.6
  percent_indicator: ^4.2.3
  dynamic_table: ^0.0.1-beta.2
  syncfusion_flutter_calendar: ^23.1.42
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  universal_html: ^2.2.4
  universal_platform: ^1.0.0+1
  connectivity_plus: ^5.0.1
  cached_network_image: ^3.3.0
  flutter_native_splash: ^2.3.8
  get: ^4.6.6
  get_storage: ^2.1.1
  logger: ^2.0.2+1
  toastification: ^1.1.0
  youtube_player_flutter: ^8.1.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/icons/
  - assets/images/
  - assets/images/icons/
  - assets/images/logos/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 800
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          style: italic